config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "/bookclubs/:id/join", to: "bookclubs#join", as: :join_bookclub

  get "/my-bookclubs/", to: "bookclubs#my_bookclubs", as: :my_bookclubs

  resources :bookclubs, only: %i[index new create show destroy] do
    resources :meetings, only: %i[new create show]
  end

  resources :meetings, only: [] do
    post "accept", to: "meetings#accept", as: "accept"
    post "decline", to: "meetings#decline", as: "decline"
  end

  resources :books, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :my_books
  has_many :users, through: :my_books
end

app/models/bookclub.rb
class Bookclub < ApplicationRecord
  has_many :meetings
  has_many :bookclub_members
  has_many :users, through: :bookclub_members
  has_many :books, through: :meetings
  has_one_attached :photo

  validates :name, presence: true
  validates :description, presence: true
  validates :photo, presence: true
end

app/models/bookclub_member.rb
class BookclubMember < ApplicationRecord
  belongs_to :user
  belongs_to :bookclub

  def admin?
    admin
  end
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :bookclub
  has_many :meeting_guests
  belongs_to :book

  enum :status, { pending: 0, accepted: 1, declined: 2 }

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/meeting_guest.rb
class MeetingGuest < ApplicationRecord
  belongs_to :user
  belongs_to :meeting
  # define meeting status
  enum :status, { pending: 0, accepted: 1, declined: 2 }
end

app/models/my_book.rb
class MyBook < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookclub_members
  has_many :bookclubs, through: :bookclub_members
  has_many :my_books
  has_many :books, through: :my_books
  has_one_attached :photo

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit::Authorization
  include Pagy::Backend

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:photo, :email, :password)}

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:photo, :email, :password, :current_password)}
  end
end

app/controllers/bookclubs_controller.rb
class BookclubsController < ApplicationController
  before_action :set_bookclub, only: %i[show destroy join]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @bookclubs = policy_scope(Bookclub)

    if params[:query].present?
      sql_subquery = "name ILIKE :query OR genre ILIKE :query"
      @bookclubs = @bookclubs.where(sql_subquery, query: "%#{params[:query]}%")
    end

    respond_to do |format|
      format.html
      format.text { render partial: "bookclubs/list", locals: { books: @bookclubs }, formats: [:html] }
    end
  end

  def show
    authorize @bookclub
    @current_meeting = @bookclub.meetings.last
    @book = @current_meeting.book if @bookclub.meetings.present?
    @is_bookclub_member = @bookclub.bookclub_members.where(user: current_user).present? || @bookclub.bookclub_members.where(user:current_user, admin:true).present?
    # search for meeting guest to display status on button (show_full_view)
    @meeting_guest = MeetingGuest.find_by(meeting_id: @current_meeting.id, user_id: current_user.id) if current_user && @current_meeting
  end

  def new
    @bookclub = Bookclub.new
    authorize @bookclub
  end

  def create
    @bookclub = Bookclub.new(bookclub_params)

    if @bookclub.save
      authorize @bookclub
      BookclubMember.create(user: current_user, bookclub: @bookclub, admin: true)
      redirect_to bookclubs_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def join
    authorize @bookclub
    BookclubMember.find_or_create_by(user: current_user, bookclub: @bookclub)
    redirect_to bookclub_path(@bookclub)
  end

  def destroy
    @bookclub.destroy
    redirect_to bookclubs_path, status: :see_other
  end

  def my_bookclubs
    #joining bookclub_members table to bookclubs table
    #filtering by bookclub_member/current_user
    @my_bookclubs = Bookclub.joins(:bookclub_members).where(bookclub_members: { user: current_user })
    authorize @my_bookclubs
  end

  private

  def set_bookclub
    @bookclub = Bookclub.find(params[:id])
  end

  def bookclub_params
    params.require(:bookclub).permit(:name, :genre, :description, :photo)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @books = policy_scope(Book)

    query = params[:query] || params[:q]

    if query.present?
      sql_subquery = "title ILIKE :query OR author ILIKE :query"
      @books = @books.where(sql_subquery, query: "%#{query}%")
    end

    @pagy, @books = pagy(@books, items: 20)

    respond_to do |format|
      format.html
      format.text { render partial: "books/list", locals: { books: @books }, formats: [:html] }
      format.json { render json: { total_count: @books.count, items: @books }, formats: [:json] }
    end
  end

  def show
    @book = Book.find(params[:id])
    authorize @book
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController

  def new
    @bookclub = Bookclub.find(params[:bookclub_id])
    authorize @bookclub
    @meeting = Meeting.new(bookclub: @bookclub)
    authorize @meeting
    @meeting.bookclub = @bookclub
  end

  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.bookclub = Bookclub.find(params[:bookclub_id])
    @meeting.status = :pending
    if @meeting.save
      authorize @meeting
      redirect_to bookclub_path(@meeting.bookclub)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def accept
    # create meeting guest and change status to "accept"
    @meeting_guest = MeetingGuest.create(meeting_id:params[:meeting_id], user_id: current_user.id)
    authorize @meeting_guest.meeting
    @meeting_guest.accepted!
    redirect_to bookclub_path(@meeting_guest.meeting.bookclub), status: :see_other
  end

  def decline
    # create meeting guest and change status to "decline"
    @meeting_guest = MeetingGuest.create(meeting_id:params[:meeting_id], user_id: current_user.id)
    authorize @meeting_guest.meeting
    @meeting_guest.declined!
    redirect_to bookclub_path(@meeting_guest.meeting.bookclub), status: :see_other
  end

  def show
    @meeting = Meeting.find(params[:id])
    authorize @meeting
  end

  private

  def meeting_params
    params.require(:meeting).permit(:book_id, :date_time, :video_link, :location)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home index show]

  def home
    @bookclubs = Bookclub.first(3)
    @meetings = Meeting.all.includes(:book).last(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/bookclubs/_show-full.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="cards col-8 d-flex flex-row mx-auto p-4 mt-5 position-relative">
      <div class="p-3">
        <%= cl_image_tag @bookclub.photo.key, height: 140, width: 140, class: "rounded-circle  shadow" %>
      </div>
      <% if @bookclub.bookclub_members.find_by(user: current_user).present? %>
        <% if @bookclub.bookclub_members.find_by(user: current_user).admin? %>
          <i class="crown-show fa-solid fa-crown fa-lg" style="color: #ffd700;"></i>
        <% end %>
      <% end %>
      <div class="d-flex flex-column ms-5">
        <div class="mt-3">
          <h5><strong><%= @bookclub.name %></strong></h5>
          <p class="num-members"><%= @bookclub.bookclub_members.size %> members</p>
        </div>
        <div class="mt-4">
          <p> <%= @bookclub.description %> </p>
        </div>
      </div>
    </div>
  </div>
  <div>
    <% if @current_meeting.nil? %>
      <div class="cards col-8 mx-auto my-5">
        <div class= "d-flex justify-content-around align-items-center">
          <div class="d-flex flex-column text-center">
            <h3 class="d-flex justify-content-center pt-5 pb-2">No books have been read yet</h3>
            <p>Create a meeting to start reading a book!</p>
          </div>
          <% if @bookclub.bookclub_members.find_by(user: current_user).admin? %>
            <%= link_to "New meeting", new_bookclub_meeting_path(@bookclub), class: "button" %>
          <% else %>
          <% end %>
          </div>
          <div>
            <%= image_tag "empty-shelf.png", class: "shelf mt-4 pb-5 d-block mx-auto" %>
          </div>
        </div>
      <% else %>
        <div>
          <% if @book.present? %>
            <div class="cards col-8 d-flex mx-auto p-4 mt-5">
              <div class="d-flex flex-column">
                <div class="d-flex flex-column text-center mt-2 mb-4">
                  <h2>Currently Reading</h2>
                </div>
                <div class="d-flex ps-3 pt-3">
                  <%= image_tag @book.image_link, height: 200, class: "shadow mb-3" %>
                  <div class="d-flex flex-column">
                    <div class="ms-5 mt-2">
                      <h4><%= @book.title %></h4>
                    </div>
                    <div class="ms-5">
                      <%= @book.author %>
                    </div>
                    <div class="ms-5 mt-1">
                      <%= @book.year %>
                    </div>
                    <div class="mx-5 mt-5 mb-3">
                      <%= @book.description %>
                    </div>
                  </div>
                </div >
              </div>
            </div>
          <% end %>
          <div class="d-flex justify-content-center mt-5 mb-4">
            <% if policy(Meeting.new(bookclub: @bookclub)).new? %>
              <%= link_to "New meeting", new_bookclub_meeting_path(@bookclub), class: "button" %>
            <% end %>
          </div>
          <div class="d-flex mx-auto col-8 ps-2">
            <ul class="nav nav-pills" role="tablist">
              <li class="nav-item" role="presentation">
                <button class="nav-link active" id="pills-next-meeting-tab" data-bs-toggle="pill" data-bs-target="#pills-next-meeting" type="button" role="tab" aria-controls="pills-next-meeting" aria-selected="true">Next Meeting</button>
              </li>
              <li class="nav-item" role="presentation">
                <button class="nav-link" id="pills-Books-weve-read-tab" data-bs-toggle="pill" data-bs-target="#pills-Books-weve-read" type="button" role="tab" aria-controls="pills-Books-weve-read" aria-selected="false">Books we've read</button>
              </li>
            </ul>
          </div>
          <div class="cards-tab col-8 d-flex flex-column mx-auto p-4 mb-5 mx-3">
            <div class="tab-content" id="pills-tabContent">
              <div class="tab-pane fade show active" id="pills-next-meeting" role="tabpanel" aria-labelledby="pills-next-meeting-tab">
                <div class="d-flex justify-content-between">
                  <p><strong>Meeting details:</strong></p>
                </div>
                <div class="d-flex mt-4 mb-4 justify-content-between align-items-center">
                  <div>
                    <% if @current_meeting.present? %>
                      <div>
                        <%= @current_meeting.location %>
                      </div>
                      <div>
                        <%= @current_meeting.video_link %>
                      </div>
                      <div>
                        <%= @current_meeting.date_time %>
                      </div>
                    </div>
                    <div class="d-flex">
                      <%# calls @meeting_guest from bookclubs_controller %>
                      <% if @meeting_guest.nil? %>
                        <div class="d-flex">
                          <%= link_to "yes", meeting_accept_path(@current_meeting), data: {turbo_method: :post}, class: "button-meet mx-2" %>
                          <%= link_to "no", meeting_decline_path(@current_meeting), data: {turbo_method: :post}, class: "button-meet" %>
                        </div>
                        <%# calls @meeting_guest from bookclubs_controller %>
                      <% elsif @meeting_guest.declined? %>
                        <div class="d-flex flex-column align-items-center">
                          <div class="button-meet mx-3">declined</div>
                        </div>
                        <%# calls @meeting_guest from bookclubs_controller %>
                      <% else @meeting_guest.accepted? %>
                        <div class="d-flex flex-column align-items-center">
                          <div class="button-meet mx-3">accepted</div>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="mt-3">
                <%# count and show accepted invites %>
                <% accepted_count = MeetingGuest.where(meeting: @current_meeting, status: 'accepted').count %>
                <p><%= accepted_count %> accepted</p>
              </div>
            </div>
            <div class="tab-pane fade" id="pills-Books-weve-read" role="tabpanel" aria-labelledby="pills-Books-weve-read-tab">
              <div class="row justify-content-center">
                <div class="col-md-auto col-sm-6 col-12 my-4 text-center">
                  <% @bookclub.meetings[0..-2].each do |meeting| %>
                    <a href="<%= book_path(meeting.book.id) %>" class="p-2">
                      <%= image_tag(meeting.book.image_link, style: "width: 100px; height: auto; box-shadow: 0px 0px 5px grey;", class: "zoom-effect") %>
                    </a>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bookclubs/_show-partial.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="cards col-8 d-flex flex-row mx-auto p-4 mt-5">
      <div class="p-3">
        <%= cl_image_tag @bookclub.photo.key, height: 140, width: 140, class: "rounded-circle  shadow" %>
      </div>
      <div class="d-flex flex-column mx-5">
        <div class="mt-3">
          <div class="d-flex justify-content-between align-items-center">
            <div class="d-flex flex-column">
              <h5><strong><%= @bookclub.name %></strong></h5>
              <p class="num-members"><%= @bookclub.bookclub_members.size %> members</p>
            </div>
            <div>
              <%= link_to "Join", join_bookclub_path(@bookclub), class: "button" %>
            </div>
          </div>
        </div>
        <div class="mt-4">
          <p> <%= @bookclub.description %> </p>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/bookclubs/_tabs.html.erb
<!-- (A) LOAD CSS + JS -->
<link href="tabs.css" rel="stylesheet">
<script src="tabs.js"></script>

<!-- (B) TABS WRAPPER -->
<div class="tabs">
  <!-- (B1) HEADERS -->
  <div class="tabHead">
    <p>Next meeting</p>
    <p>Books we've read</p>
  </div>

  <!-- (B2) CONTENTS -->
  <div class="tabBody">
    <div class="cards-tab col-8 d-flex flex-column mx-auto p-4 mb-5 mx-3">
      <div class="d-flex justify-content-between">
        <p><strong>Next meeting details:</strong></p>
      </div>
      <div class="d-flex mt-4 mb-4 justify-content-between align-items-center">
        <div>
          <% if @current_meeting.present? %>
            <div>
              <%= @current_meeting.location %>
            </div>
            <div>
              <%= @current_meeting.video_link %>
            </div>
            <div>
              <%= @current_meeting.date_time %>
            </div>
          </div>
          <div class="d-flex">
            <% if @current_meeting.pending? %>
              <div class="d-flex">
                <%= link_to "yes", meeting_accept_path(@current_meeting), data: {turbo_method: :post}, class: "button-meet mx-2" %>
                <%= link_to "no", meeting_decline_path(@current_meeting), data: {turbo_method: :post}, class: "button-meet" %>
              </div>
            <% elsif @current_meeting.declined? %>
              <div class="d-flex">
                <div class="button-meet mx-3">declined</div>
              </div>
            <% else @current_meeting.accepted? %>
              <div class="d-flex">
                <div class="button-meet mx-3">accepted</div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookclubs/my_bookclubs.html.erb
<div class="container mt-5">
  <div class="d-flex justify-content-center mb-4">
    <h1>My Clubs</h1>
  </div>
  <div class="container">
    <div class="row d-flex justify-content-center mb-4">
      <div class="col-10">
        <% if @my_bookclubs.present? %>
          <% @my_bookclubs.each do |my_bookclub| %>
            <div class="cards col-12 border-2 rounded-3 my-3 shadow p-4 alig-items-center position-relative">
              <div class="d-flex justify-content-between align-items-center">
                <% if my_bookclub.photo.attached?%>
                  <% if my_bookclub.bookclub_members.find_by(user: current_user).present? %>
                    <% if my_bookclub.bookclub_members.find_by(user: current_user).admin? %>
                      <%= cl_image_tag my_bookclub.photo.key, height: 140, width: 140, class: "image rounded-circle mb-4" %>
                    <% else %>
                      <%= cl_image_tag my_bookclub.photo.key, height: 140, width: 140, class: "rounded-circle mb-4" %>
                    <% end %>
                  <% end %>
                <% end %>
                <% if my_bookclub.bookclub_members.find_by(user: current_user).admin? %>
                  <i class="crown-clubs fa-solid fa-crown fa-lg" style="color: #ffd700;"></i>
                <% end %>
                <%= link_to "Go", bookclub_path(my_bookclub), class: "button-myclubs" %>
                <div class="container justify-content-between">
                  <div class="text-start mx-4 ">
                    <h5><strong><%= my_bookclub.name %></strong></h5>
                  </div>
                  <p class="desc-myclubs"> <%= my_bookclub.description %></p>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <h5 class="empty-state"> <%= link_to "Start", new_bookclub_path, class: "link-color" %> or <%= link_to "Join", bookclubs_path, class: "link-color" %> a Book Club </h5>
          <%= image_tag "my_clubs_image.png", class: "my_clubs d-flex mx-auto" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container mt-5">
  <div data-controller="search-books">
    <div class="d-flex justify-content-center mb-4">
      <h1>Find a Book</h1>
    </div>
    <div class="d-flex justify-content-center">
      <div class="col-6">
        <%= form_with url: books_path, method: :get, html: {class:"flex-grow-1 mb-4", data: {search_books_target: "form"}} do |f| %>
          <%= f.text_field  :query,
                            class: "form-control rounded-pill",
                            placeholder: "Search by Title or Author",
                            value: params[:query],
                            autocomplete: :off,
                            data: {search_books_target: "input",
                            action: "keyup->search-books#update"}
          %>
        <% end %>
      </div>
    </div>
    <div class="container mt-5">
      <div class="row">
        <div class="col-8 mx-auto">
          <div data-search-books-target="list">
            <%= render partial: 'books/list', locals: { books: @books } %>
          </div>
          <div class="pag-bar mt-5 pt-5">
            <%== pagy_bootstrap_nav(@pagy) %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(<%= asset_url "banner_home" %>);">
  <div class="container">
    <div class="d-flex flex-direction-column justify-content-between">
      <div class="white">
      </div>
      <div class="mt-4">
        <div class="container">
          <h1 class="text-white"><strong>Read a Book. Together.</strong></h1>
          <div class="mt-2">
            <p style="margin-bottom: 0">Connect Through Words, Virtually and In Person.</p>
          </div>
          <div class="mt-3">
            <%= link_to "Start a Book Club", new_bookclub_path, class: "button shadow" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container mt-5">
  <div class="cards-home">
    <div class="d-flex justify-content-center m-3">
      <h4>Join a Book Club</h4>
    </div>
    <div class="row">
      <% @bookclubs.each do |bookclub| %>
        <div class="col cards mt-1 shadow p-4 m-4">
          <div class="h-100">
            <div class="content">
              <div class="row">
                <div class="col-12 justify-content-center position-relative">
                  <% if bookclub.photo.attached? %>
                    <% if current_user && bookclub.bookclub_members.find_by(user: current_user).present? %>
                      <% if current_user && bookclub.bookclub_members.find_by(user: current_user).admin? %>
                        <%= cl_image_tag bookclub.photo.key, height: 140, width: 140, class: "image rounded-circle mb-4" %>
                        <i class="crown-home fa-solid fa-crown fa-lg" style="color: #ffd700;"></i>
                      <% else %>
                        <%= cl_image_tag bookclub.photo.key, height: 140, width: 140, class: "rounded-circle mb-4" %>
                      <% end %>
                    <% else %>
                      <%= cl_image_tag bookclub.photo.key, height: 140, width: 140, class: "rounded-circle mb-4" %>
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="row">
                <h5 class="mb-4 text-center"><%= bookclub.name %></h5>
                <div class="content-text mt-2">
                  <% if bookclub.description.chars.count > 300 %>
                    <p>
                      <%= bookclub.description.first(300) + "..." %>
                    </p>
                  <% else %>
                    <p class="text-center"><%= bookclub.description %></p>
                  <% end %>
                </div>
                <% if bookclub.books.present? %>
                  <p class="text-center mt-4"><strong>Currently reading</strong></p>
                  <div class="w-50 d-flex justify-content-center mx-auto mb-3">
                    <%=image_tag bookclub.books.last.image_link %>
                  </div>
                <% else %>
                  <p class="text-center mt-4"><strong>Currently not reading a book.</strong></p>
                  <div>
                    <%= image_tag "Young_woman.png", class: "woman mb-3 d-block mx-auto" %>
                  </div>
                <% end %>
                <div class="d-flex flex-column justify-content-center mt-3">
                  <% if bookclub.bookclub_members.where(user: current_user).empty? %>
                    <div class="d-flex flex-column text-center justify-content-end">
                      <div>
                        <%= link_to "Join", join_bookclub_path(bookclub), class: "button" %>
                      </div>
                      <%= link_to "Learn More", bookclub_path(bookclub), class: "learn-btn pt-3 text-decoration-none w-auto" %>
                    </div>
                  <% else %>
                    <div class="text-center">
                      <%= link_to "Learn More", bookclub_path(bookclub), class: "learn-btn pt-3 text-decoration-none w-auto" %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="d-flex justify-content-center p-5">
      <%= link_to "Browse all", bookclubs_path, class: "button-secondary" %>
    </div>
  </div>
</div>
<div class="container">
  <div class="d-flex justify-content-center mb-4">
    <h4>Recommendations</h4>
  </div>
  <div class="d-flex justify-content-center mb-3">
    <p class="text-center">June's Must-Reads: Dive into Enchanting Stories. Click for Literary Bliss!</p>
  </div>
  <div class="row justify-content-center">
    <div class="col-md-auto col-sm-6 col-12 mb-4 text-center">
      <% @meetings.each do |meeting| %>
        <a href="<%= book_path(meeting.book.id) %>" class="p-2">
          <%= image_tag(meeting.book.image_link, style: "width: 150px; height: auto; box-shadow: 0px 0px 5px grey;", class: "zoom-effect") %>
        </a>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logoBig.png", class: "logo ms-2" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <%# <li class="nav-item active"> %>
            <%# <%= link_to "Home", root_path, class: "nav-link mx-4" %>
          <%# </li> %>
          <li class="nav-item active">
            <%= link_to "Join a Book Club", bookclubs_path, class: "join-link nav-link mx-4" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Find a Book", books_path, class: "nav-link mx-4" %>
          </li>
          <li class="nav-item active">
            <%= link_to "My Clubs", my_bookclubs_path, class: "nav-link mx-4" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if current_user.photo.attached?%>
            <%= cl_image_tag current_user.photo.key, width: 40, height: 40, crop: :fill, gravity: :face, class: "avatar", alt: "dropdown menu" %>
          <% else %>
            <%= image_tag "https://www.seekpng.com/png/full/110-1100707_person-avatar-placeholder.png", class: "avatar", alt: "dropdown menu" %>
          <% end %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <%# <li class="nav-item active"> %>
            <%# <%= link_to "Home", root_path, class: "nav-link mx-4" %>
          <%# </li> %>
          <li class="nav-item active">
            <%= link_to "Join a Bookclub", bookclubs_path(@bookclub), class: "join-link nav-link mx-4" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Find a Book", books_path, class: "nav-link mx-4" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link mx-4" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path,style: "padding: 8px 24px", class: "button nav-link mx-4 shadow" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>